### ISSUE TITLE
Table beautification

### ISSUE THREAD

**Issue by IanHopkinson** [scraperwiki/MOT-app#7]
Bootstrap has a nice stripey table class (class="table table-striped"), and the whole of the results page should probably go in a container, as for the front page.

We should apply it to pages like:
https://mot.scraperwiki.com/FAULTS/TOYOTA/PRIUS
and
https://mot.scraperwiki.com/FAULTS/TOYOTA/PRIUS/Tread%20depth

**Comment by piusokoh** [comment]
Tables beautified to a reasonable extent.
